### Taller 1: Conexión de Pandas con Bases de Datos
ejercicios prácticos

In [42]:
# Asegurar instalación de todas las dependencias requeridas en el kernel activo
%pip install pandas sqlalchemy pymysql oracledb pymongo

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.0.49)
Requirement already satisfied: pymysql in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.1.3)
Requirement already satisfied: oracledb in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.0.0)
Requirement already satisfied: pymongo in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.17.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: cryptography>=3.2.1 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from oracledb) (48.0.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pymongo) (2.8.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cryptography>=3.2.1->oracledb) (2.0.0)
Requirement already satisfied: pycparser in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from cffi>=2.0.0->cryptography>=3.2.1->oracledb) (3.0)
Requirement already satisfied: six>=1.5 in C:\Users\lvfm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\lvfm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

##  Conexión al DBMS MariaDB

In [43]:
from sqlalchemy import create_engine
import pandas as pd

# Create engine para MariaDB
engine_maria = create_engine("mysql+pymysql://usuario:contrasena@localhost:3307/gestion_emp")

# Execute query and store records in DataFrame
df_maria = pd.read_sql_query("select * from departments", engine_maria)
print(df_maria)

    department_id       department_name  manager_id location_id
0              10        Administration       200.0        None
1              20             Marketing       201.0        None
2              30            Purchasing       114.0        None
3              40       Human Resources       203.0        None
4              50              Shipping       121.0        None
5              60                    IT       103.0        None
6              70      Public Relations       204.0        None
7              80                 Sales       145.0        None
8              90             Executive       100.0        None
9             100               Finance       108.0        None
10            110            Accounting       205.0        None
11            120              Treasury         NaN        None
12            130         Corporate Tax         NaN        None
13            140    Control And Credit         NaN        None
14            150  Shareholder Services         NaN        None
15            160              Benefits         NaN        None
16            170         Manufacturing         NaN        None
17            180          Construction         NaN        None
18            190           Contracting         NaN        None
19            200            Operations         NaN        None
20            210            IT Support         NaN        None
21            220                   NOC         NaN        None
22            230           IT Helpdesk         NaN        None
23            240      Government Sales         NaN        None
24            250          Retail Sales         NaN        None
25            260            Recruiting         NaN        None
26            270               Payroll         NaN        None

## Conexión al DBMS Oracle (Modo Thin)

In [44]:
from sqlalchemy import create_engine
import pandas as pd

# Usamos oracle+oracledb para soporte Thin 100% portable y directo en Python
engine_oracle = create_engine("oracle+oracledb://hr:uptc@localhost:1521/?service_name=uptc")

# Execute query and store records in DataFrame
df_oracle = pd.read_sql_query("select * from departments", engine_oracle)
print(df_oracle)

    department_id       department_name  manager_id location_id
0              10        Administration       200.0        None
1              20             Marketing       201.0        None
2              30            Purchasing       114.0        None
3              40       Human Resources       203.0        None
4              50              Shipping       121.0        None
5              60                    IT       103.0        None
6              70      Public Relations       204.0        None
7              80                 Sales       145.0        None
8              90             Executive       100.0        None
9             100               Finance       108.0        None
10            110            Accounting       205.0        None
11            120              Treasury         NaN        None
12            130         Corporate Tax         NaN        None
13            140    Control And Credit         NaN        None
14            150  Shareholder Services         NaN        None
15            160              Benefits         NaN        None
16            170         Manufacturing         NaN        None
17            180          Construction         NaN        None
18            190           Contracting         NaN        None
19            200            Operations         NaN        None
20            210            IT Support         NaN        None
21            220                   NOC         NaN        None
22            230           IT Helpdesk         NaN        None
23            240      Government Sales         NaN        None
24            250          Retail Sales         NaN        None
25            260            Recruiting         NaN        None
26            270               Payroll         NaN        None

--- 
##  Ejercicios SQL sobre el esquema HR en Oracle

A continuación se presenta la solución de los ejercicios 1 al 15 consultando directamente la base de datos Oracle Xe.

### 1. Proyectar el nombre, apellido y salario de todos los empleados de la base de datos.

In [45]:
query = "SELECT first_name, last_name, salary FROM employees"
df1 = pd.read_sql_query(query, engine_oracle)
df1

    first_name last_name   salary
0       Steven      King  24000.0
1        Neena   Kochhar  17000.0
2          Lex   De Haan  17000.0
3    Alexander    Hunold   9000.0
4        Bruce     Ernst   6000.0
..         ...       ...      ...
101        Pat       Fay   6000.0
102      Susan    Mavris   6500.0
103    Hermann      Baer  10000.0
104    Shelley   Higgins  12000.0
105    William     Gietz   8300.0

[106 rows x 3 columns]

### 2. Proyectar el código y nombre de los departamentos.

In [46]:
query = "SELECT department_id, department_name FROM departments"
df2 = pd.read_sql_query(query, engine_oracle)
df2

    department_id       department_name
0              10        Administration
1              20             Marketing
2              30            Purchasing
3              40       Human Resources
4              50              Shipping
5              60                    IT
6              70      Public Relations
7              80                 Sales
8              90             Executive
9             100               Finance
10            110            Accounting
11            120              Treasury
12            130         Corporate Tax
13            140    Control And Credit
14            150  Shareholder Services
15            160              Benefits
16            170         Manufacturing
17            180          Construction
18            190           Contracting
19            200            Operations
20            210            IT Support
21            220                   NOC
22            230           IT Helpdesk
23            240      Government Sales
24            250          Retail Sales
25            260            Recruiting
26            270               Payroll

### 3. Seleccionar los empleados cuyo salario sea superior a 10.000 dólares.

In [47]:
query = "SELECT * FROM employees WHERE salary > 10000"
df3 = pd.read_sql_query(query, engine_oracle)
df3

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,NaN,NaN,90
1,101,Neena,Kochhar,NKOCHHAR,5.151.234.568,2018-07-16,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,5.151.234.569,2012-08-21,AD_VP,17000.0,NaN,100.0,90
3,108,Nancy,Greenberg,NGREENBE,5.151.244.569,2020-10-20,FI_MGR,12000.0,NaN,101.0,100
4,114,Den,Raphaely,DRAPHEAL,5.151.274.561,2020-12-27,PU_MAN,11000.0,NaN,100.0,30
5,145,John,Russell,JRUSSEL,011.44.1344.429268,2021-05-24,SA_MAN,14000.0,0.40,100.0,80
6,146,Karen,Partners,KPARTNER,011.44.1344.467268,2012-05-25,SA_MAN,13500.0,0.30,100.0,80
7,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,2015-05-31,SA_MAN,12000.0,0.30,100.0,80
8,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,2014-04-16,SA_MAN,11000.0,0.30,100.0,80
9,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,2014-08-22,SA_MAN,10500.0,0.20,100.0,80
10,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,2020-04-19,SA_REP,10500.0,0.25,147.0,80
11,168,Lisa,Ozer,LOZER,011.44.1343.929268,2018-12-01,SA_REP,11500.0,0.25,148.0,80
12,201,Michael,Hartstein,MHARTSTE,5.151.235.555,2017-06-08,MK_MAN,13000.0,NaN,100.0,20
13,205,Shelley,Higgins,SHIGGINS,5.151.238.080,2014-10-06,AC_MGR,12000.0,NaN,101.0,110

### 4. Ordenar los empleados por salario. Mostrar de forma ascendente y descendente.

In [48]:
df_desc = pd.read_sql_query("SELECT * FROM employees ORDER BY salary DESC", engine_oracle)
df_asc = pd.read_sql_query("SELECT * FROM employees ORDER BY salary ASC", engine_oracle)

print("--- ORDENADO DESCENDENTE ---")
display(df_desc.head(5))
print("\n--- ORDENADO ASCENDENTE ---")
display(df_asc.head(5))

--- ORDENADO DESCENDENTE ---

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,NaN,NaN,90.0
1,102,Lex,De Haan,LDEHAAN,5.151.234.569,2012-08-21,AD_VP,17000.0,NaN,100.0,90.0
2,101,Neena,Kochhar,NKOCHHAR,5.151.234.568,2018-07-16,AD_VP,17000.0,NaN,100.0,90.0
3,145,John,Russell,JRUSSEL,011.44.1344.429268,2021-05-24,SA_MAN,14000.0,0.4,100.0,80.0
4,146,Karen,Partners,KPARTNER,011.44.1344.467268,2012-05-25,SA_MAN,13500.0,0.3,100.0,80.0

--- ORDENADO ASCENDENTE ---

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,132,TJ,Olson,TJOLSON,6.501.248.234,2019-10-31,ST_CLERK,2100.0,NaN,121.0,50.0
1,128,Steven,Markle,SMARKLE,6.501.241.434,2013-05-02,ST_CLERK,2200.0,NaN,120.0,50.0
2,136,Hazel,Philtanker,HPHILTAN,6.501.271.634,2019-04-23,ST_CLERK,2200.0,NaN,122.0,50.0
3,127,James,Landry,JLANDRY,6.501.241.334,2018-01-09,ST_CLERK,2400.0,NaN,120.0,50.0
4,135,Ki,Gee,KGEE,6.501.271.734,2017-10-15,ST_CLERK,2400.0,NaN,122.0,50.0

### 5. Mostrar los empleados cuyo nombre inicien por la letra L.

In [49]:
query = "SELECT * FROM employees WHERE LOWER(first_name) LIKE 'l%'"
df5 = pd.read_sql_query(query, engine_oracle)
df5

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,102,Lex,De Haan,LDEHAAN,5.151.234.569,2012-08-21,AD_VP,17000.0,NaN,100,90
1,113,Luis,Popp,LPOPP,5.151.244.567,2021-01-20,FI_ACCOUNT,6900.0,NaN,108,100
2,129,Laura,Bissot,LBISSOT,6.501.245.234,2021-04-10,ST_CLERK,3300.0,NaN,121,50
3,159,Lindsey,Smith,LSMITH,011.44.1345.729268,2021-09-08,SA_REP,8000.0,0.30,146,80
4,160,Louise,Doran,LDORAN,011.44.1345.629268,2015-09-15,SA_REP,7500.0,0.30,146,80
5,168,Lisa,Ozer,LOZER,011.44.1343.929268,2018-12-01,SA_REP,11500.0,0.25,148,80

### 6. Consultar la cantidad de empleados de la Base de Datos.

In [50]:
query = "SELECT COUNT(*) AS total_empleados FROM employees"
df6 = pd.read_sql_query(query, engine_oracle)
df6

   total_empleados
0              106

### 7. Consultar la cantidad de empleados por cada uno de los departamentos.

In [51]:
query = """
SELECT e.department_id, d.department_name, COUNT(*) AS qty_employees 
FROM employees e 
LEFT JOIN departments d ON e.department_id = d.department_id 
GROUP BY e.department_id, d.department_name 
ORDER BY e.department_id
"""
df7 = pd.read_sql_query(query, engine_oracle)
df7

    department_id   department_name  qty_employees
0            10.0    Administration              1
1            20.0         Marketing              2
2            30.0        Purchasing              6
3            40.0   Human Resources              1
4            50.0          Shipping             45
5            60.0                IT              5
6            70.0  Public Relations              1
7            80.0             Sales             33
8            90.0         Executive              3
9           100.0           Finance              6
10          110.0        Accounting              2
11            NaN               NaN              1

### 8. ¿Cuál es el empleado con el mayor salario de la organización?

In [52]:
query = "SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees)"
df8 = pd.read_sql_query(query, engine_oracle)
df8

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,None,None,90

### 9. ¿Cuál es el promedio del salario de los empleados?

In [53]:
query = "SELECT ROUND(AVG(salary), 2) AS promedio_salario FROM employees"
df9 = pd.read_sql_query(query, engine_oracle)
df9

   promedio_salario
0           6418.87

### 10. ¿Cuál es el promedio del salario de los empleados por departamento?

In [54]:
query = """
SELECT e.department_id, d.department_name, ROUND(AVG(e.salary), 2) AS avg_salary 
FROM employees e 
LEFT JOIN departments d ON e.department_id = d.department_id 
GROUP BY e.department_id, d.department_name 
ORDER BY e.department_id
"""
df10 = pd.read_sql_query(query, engine_oracle)
df10

    department_id   department_name  avg_salary
0            10.0    Administration     4400.00
1            20.0         Marketing     9500.00
2            30.0        Purchasing     4150.00
3            40.0   Human Resources     6500.00
4            50.0          Shipping     3475.56
5            60.0                IT     5760.00
6            70.0  Public Relations    10000.00
7            80.0             Sales     8893.94
8            90.0         Executive    19333.33
9           100.0           Finance     8600.00
10          110.0        Accounting    10150.00
11            NaN               NaN     7000.00

### 11. Cantidad de empleados que iniciaron a trabajar en la organización por cada uno de los meses del año.

In [55]:
query = """
SELECT EXTRACT(MONTH FROM hire_date) AS mes, COUNT(*) AS cantidad_empleados 
FROM employees 
GROUP BY EXTRACT(MONTH FROM hire_date) 
ORDER BY mes
"""
df11 = pd.read_sql_query(query, engine_oracle)
df11

    mes  cantidad_empleados
0     1                  10
1     2                  12
2     3                   7
3     4                  14
4     5                   9
5     6                   6
6     7                   5
7     8                   9
8     9                   8
9    10                   6
10   11                   7
11   12                  13

### 12. Empleados cuyo nombre inicia con "st".

In [56]:
query = "SELECT * FROM employees WHERE LOWER(first_name) LIKE 'st%'"
df12 = pd.read_sql_query(query, engine_oracle)
df12

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,None,NaN,90
1,128,Steven,Markle,SMARKLE,6.501.241.434,2013-05-02,ST_CLERK,2200.0,None,120.0,50
2,138,Stephen,Stiles,SSTILES,6.501.212.034,2019-02-18,ST_CLERK,3200.0,None,123.0,50

### 13. Empleados donde el nombre termina en la letra "s".

In [57]:
query = "SELECT * FROM employees WHERE LOWER(first_name) LIKE '%s'"
df13 = pd.read_sql_query(query, engine_oracle)
df13

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,113,Luis,Popp,LPOPP,5.151.244.567,2021-01-20,FI_ACCOUNT,6900.0,NaN,108,100
1,127,James,Landry,JLANDRY,6.501.241.334,2018-01-09,ST_CLERK,2400.0,NaN,120,50
2,131,James,Marlow,JAMRLOW,6.501.247.234,2018-09-06,ST_CLERK,2500.0,NaN,121,50
3,142,Curtis,Davies,CDAVIES,6.501.212.994,2015-12-20,ST_CLERK,3100.0,NaN,124,50
4,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,2013-01-01,SA_REP,6200.0,0.1,149,80
5,185,Alexis,Bull,ABULL,6.505.092.876,2016-09-08,SH_CLERK,4100.0,NaN,121,50
6,199,Douglas,Grant,DGRANT,6.505.079.844,2015-03-27,SH_CLERK,2600.0,NaN,124,50

### 14. Empleados cuyo nombre contiene la cadena "mar".

In [58]:
query = "SELECT * FROM employees WHERE LOWER(first_name) LIKE '%mar%'"
df14 = pd.read_sql_query(query, engine_oracle)
df14

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,182,Martha,Sullivan,MSULLIVA,6.505.079.878,2015-06-21,SH_CLERK,2500.0,None,120,50

### 15. Empleados donde el nombre contiene vocal "i" o "u" y también la consonante "s". Utilizando expresiones regulares.

In [59]:
query = "SELECT employee_id, first_name, last_name FROM employees WHERE REGEXP_LIKE(first_name, '([iu].*s|s.*[iu])', 'i')"
df15 = pd.read_sql_query(query, engine_oracle)
df15

    employee_id   first_name last_name
0           111       Ismael   Sciarra
1           112  Jose Manuel     Urman
2           113         Luis      Popp
3           116       Shelli     Baida
4           117        Sigal    Tobias
5           140       Joshua     Patel
6           142       Curtis    Davies
7           153  Christopher     Olsen
8           159      Lindsey     Smith
9           160       Louise     Doran
10          166       Sundar      Ande
11          168         Lisa      Ozer
12          169     Harrison     Bloom
13          173      Sundita     Kumar
14          180      Winston    Taylor
15          185       Alexis      Bull
16          194       Samuel    McCain
17          199      Douglas     Grant
18          203        Susan    Mavris

### 16. Automatizar en una lista de cadenas cada una de las consultas anteriores, como arreglo de consultas en Pandas

In [60]:
queries = [
    "SELECT first_name, last_name, salary FROM employees",  # 1
    "SELECT department_id, department_name FROM departments",  # 2
    "SELECT * FROM employees WHERE salary > 10000",  # 3
    "SELECT * FROM employees ORDER BY salary DESC",  # 4 (desc)
    "SELECT * FROM employees ORDER BY salary ASC",  # 4 (asc)
    "SELECT * FROM employees WHERE LOWER(first_name) LIKE 'l%'",  # 5 (L...)
    "SELECT COUNT(*) AS total_empleados FROM employees",  # 6
    "SELECT e.department_id, d.department_name, COUNT(*) AS qty_employees FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id GROUP BY e.department_id, d.department_name ORDER BY e.department_id",  # 7
    "SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees)",  # 8
    "SELECT ROUND(AVG(salary), 2) AS promedio_salario FROM employees",  # 9
    "SELECT e.department_id, d.department_name, ROUND(AVG(e.salary), 2) AS avg_salary FROM employees e LEFT JOIN departments d ON e.department_id = d.department_id GROUP BY e.department_id, d.department_name ORDER BY e.department_id",  # 10
    "SELECT EXTRACT(MONTH FROM hire_date) AS mes, COUNT(*) AS cantidad_empleados FROM employees GROUP BY EXTRACT(MONTH FROM hire_date) ORDER BY mes",  # 11
    "SELECT * FROM employees WHERE LOWER(first_name) LIKE 'st%'",  # 12
    "SELECT * FROM employees WHERE LOWER(first_name) LIKE '%s'",  # 13
    "SELECT * FROM employees WHERE LOWER(first_name) LIKE '%mar%'",  # 14
    "SELECT employee_id, first_name, last_name FROM employees WHERE REGEXP_LIKE(first_name, '([iu].*s|s.*[iu])', 'i')"  # 15
]

print(" Ejecutando automatización de consultas con Pandas...")
for idx, q in enumerate(queries, 1):
    df_result = pd.read_sql_query(q, engine_oracle)
    print(f"\n==========================================================")
    print(f" CONSULTA {idx}: {q[:75]}...")
    print(f"==========================================================")
    display(df_result.head(3))

 Ejecutando automatización de consultas con Pandas...

==========================================================
 CONSULTA 1: SELECT first_name, last_name, salary FROM employees...
==========================================================

  first_name last_name   salary
0     Steven      King  24000.0
1      Neena   Kochhar  17000.0
2        Lex   De Haan  17000.0

==========================================================
 CONSULTA 2: SELECT department_id, department_name FROM departments...
==========================================================

   department_id department_name
0             10  Administration
1             20       Marketing
2             30      Purchasing

==========================================================
 CONSULTA 3: SELECT * FROM employees WHERE salary > 10000...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,NaN,NaN,90
1,101,Neena,Kochhar,NKOCHHAR,5.151.234.568,2018-07-16,AD_VP,17000.0,NaN,100.0,90
2,102,Lex,De Haan,LDEHAAN,5.151.234.569,2012-08-21,AD_VP,17000.0,NaN,100.0,90

==========================================================
 CONSULTA 4: SELECT * FROM employees ORDER BY salary DESC...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,NaN,NaN,90.0
1,102,Lex,De Haan,LDEHAAN,5.151.234.569,2012-08-21,AD_VP,17000.0,NaN,100.0,90.0
2,101,Neena,Kochhar,NKOCHHAR,5.151.234.568,2018-07-16,AD_VP,17000.0,NaN,100.0,90.0

==========================================================
 CONSULTA 5: SELECT * FROM employees ORDER BY salary ASC...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,132,TJ,Olson,TJOLSON,6.501.248.234,2019-10-31,ST_CLERK,2100.0,NaN,121.0,50.0
1,128,Steven,Markle,SMARKLE,6.501.241.434,2013-05-02,ST_CLERK,2200.0,NaN,120.0,50.0
2,136,Hazel,Philtanker,HPHILTAN,6.501.271.634,2019-04-23,ST_CLERK,2200.0,NaN,122.0,50.0

==========================================================
 CONSULTA 6: SELECT * FROM employees WHERE LOWER(first_name) LIKE 'l%'...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,102,Lex,De Haan,LDEHAAN,5.151.234.569,2012-08-21,AD_VP,17000.0,NaN,100,90
1,113,Luis,Popp,LPOPP,5.151.244.567,2021-01-20,FI_ACCOUNT,6900.0,NaN,108,100
2,129,Laura,Bissot,LBISSOT,6.501.245.234,2021-04-10,ST_CLERK,3300.0,NaN,121,50

==========================================================
 CONSULTA 7: SELECT COUNT(*) AS total_empleados FROM employees...
==========================================================

   total_empleados
0              106

==========================================================
 CONSULTA 8: SELECT e.department_id, d.department_name, COUNT(*) AS qty_employees FROM e...
==========================================================

   department_id department_name  qty_employees
0           10.0  Administration              1
1           20.0       Marketing              2
2           30.0      Purchasing              6

==========================================================
 CONSULTA 9: SELECT * FROM employees WHERE salary = (SELECT MAX(salary) FROM employees)...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,None,None,90

==========================================================
 CONSULTA 10: SELECT ROUND(AVG(salary), 2) AS promedio_salario FROM employees...
==========================================================

   promedio_salario
0           6418.87

==========================================================
 CONSULTA 11: SELECT e.department_id, d.department_name, ROUND(AVG(e.salary), 2) AS avg_s...
==========================================================

   department_id department_name  avg_salary
0           10.0  Administration      4400.0
1           20.0       Marketing      9500.0
2           30.0      Purchasing      4150.0

==========================================================
 CONSULTA 12: SELECT EXTRACT(MONTH FROM hire_date) AS mes, COUNT(*) AS cantidad_empleados...
==========================================================

   mes  cantidad_empleados
0    1                  10
1    2                  12
2    3                   7

==========================================================
 CONSULTA 13: SELECT * FROM employees WHERE LOWER(first_name) LIKE 'st%'...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,5.151.234.567,2021-02-23,AD_PRES,24000.0,None,NaN,90
1,128,Steven,Markle,SMARKLE,6.501.241.434,2013-05-02,ST_CLERK,2200.0,None,120.0,50
2,138,Stephen,Stiles,SSTILES,6.501.212.034,2019-02-18,ST_CLERK,3200.0,None,123.0,50

==========================================================
 CONSULTA 14: SELECT * FROM employees WHERE LOWER(first_name) LIKE '%s'...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,113,Luis,Popp,LPOPP,5.151.244.567,2021-01-20,FI_ACCOUNT,6900.0,NaN,108,100
1,127,James,Landry,JLANDRY,6.501.241.334,2018-01-09,ST_CLERK,2400.0,NaN,120,50
2,131,James,Marlow,JAMRLOW,6.501.247.234,2018-09-06,ST_CLERK,2500.0,NaN,121,50

==========================================================
 CONSULTA 15: SELECT * FROM employees WHERE LOWER(first_name) LIKE '%mar%'...
==========================================================

,employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,commission_pct,manager_id,department_id
0,182,Martha,Sullivan,MSULLIVA,6.505.079.878,2015-06-21,SH_CLERK,2500.0,None,120,50

==========================================================
 CONSULTA 16: SELECT employee_id, first_name, last_name FROM employees WHERE REGEXP_LIKE(...
==========================================================

   employee_id   first_name last_name
0          111       Ismael   Sciarra
1          112  Jose Manuel     Urman
2          113         Luis      Popp

--- 
## Ejercicios MongoDB sobre la colección "personTab"

In [61]:
from pymongo import MongoClient
from pandas import DataFrame

# Conexión a MongoDB con autenticación en la base admin
MONGO_URI = "mongodb://admin:adminpassword@localhost:27017/?authSource=admin"
client = MongoClient(MONGO_URI)
db = client['PersonDB']
collect = db['personTab']

print("-------Nombre de la base de datos---------")
print(db.name)
print()
print("----------Colecciones de la Base de Datos---------")
print(db.list_collection_names())
print()
print("-----------Primer documento de la colección-------")
print(collect.find_one())

-------Nombre de la base de datos---------
PersonDB

----------Colecciones de la Base de Datos---------
['personTab']

-----------Primer documento de la colección-------
{'_id': ObjectId('6a0bafa8c6576c400d9df8a3'), 'name': 'John Doe', 'age': 35, 'eyeColor': 'blue', 'gender': 'male', 'favoriteFruit': 'banana'}

### MongoDB - Ejercicio 9: ¿Cuántas personas tienen ojos de color café (brown) y cuya edad sea 29 años o más?

In [62]:
query_9 = {"eyeColor": "brown", "age": {"$gte": 29}}
count_9 = collect.count_documents(query_9)
print(f"La cantidad de personas con ojos cafe y edad >= 29 es: {count_9}")

La cantidad de personas con ojos cafe y edad >= 29 es: 4

### MongoDB - Ejercicio 10: ¿Qué mujeres (female) tienen como fruta favorita la manzana (apple)?

In [63]:
query_10 = {"gender": "female", "favoriteFruit": "apple"}
project_10 = {"_id": 0, "name": 1, "age": 1, "gender": 1, "favoriteFruit": 1}

cursor_10 = collect.find(query_10, project_10)
df_10 = DataFrame(list(cursor_10))
df_10

              name  age  gender favoriteFruit
0       Jane Smith   38  female         apple
1    Emily Johnson   29  female         apple
2  Sophia Martinez   45  female         apple